elections/config/routes.rb
Rails.application.routes.draw do
get 'static/index'

devise_for :admin_users, ActiveAdmin::Devise.config
ActiveAdmin.routes(self)
resource :user_session, :only => [:new, :create, :destroy]
resources :users
resources :votes
resources :committees_provinces
resources :committees
resources :provinces
get 'provinces/:id/frekwencja' => 'provinces#frekwencja', :as => :provinces_frekwencja
resources :constituencies
get 'constituencies/:id/frekwencja' => 'constituencies#frekwencja', :as => :constituencies_frekwencja
resources :form
get 'list' => 'form#list', :as => :list
resources :formtwo, :only => [:index, :edit]
root :to => 'static#index'
get 'login' => 'user_sessions#new', :as => :login
get 'logout' => 'user_sessions#destroy', :as => :logout

end

elections/app/models/province.rb
class Province < ActiveRecord::Base
 validates :name, presence: true,  length: {minimum: 7}
 validates :mandate_number, presence: true, numericality: true
 validates :authorized_number, presence: true, numericality: true

end

elections/app/controllers/provinces_controller.rb
class ProvincesController < InheritedResources::Base
#load_and_authorize_resource
#def index
#  @provinces = Provinces.all
#end

def new
  @provinces = Provinces.new
end

def create 
end
def frekwencja 
	@prov = Province.find_by_id(params[:id]) 
	@constituency = Constituency.where("province_id = ? AND given_cards IS NOT NULL", params[:id]) 
	@voters = @constituency.sum(:authorized_number) 
	@cards = @constituency.sum(:given_cards) 
	if @voters != 0 && @cards!=0 
		@frekwencja = @cards*100/@voters 
	else 
		@frekwencja = 0 
	end 
end

  private

    def province_params
      params.require(:province).permit(:name, :mandate_number, :authorized_number)
    end
end

elections/app/helpers/provinces_helper.rb
module ProvincesHelper
end

elections/app/views/provinces/_form.html.erb
<%= form_for(@province) do |f| %>
  <% if @province.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@province.errors.count, "error") %> prohibited this province from being saved:</h2>

      <ul>
      <% @province.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mandate_number %><br>
    <%= f.number_field :mandate_number %>
  </div>
  <div class="field">
    <%= f.label :authorized_number %><br>
    <%= f.number_field :authorized_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

elections/app/views/provinces/edit.html.erb
<h1>Editing Province</h1>

<%= render 'form' %>

<%= link_to 'Show', @province %> |
<%= link_to 'Back', provinces_path %>

elections/app/views/provinces/frekwencja.html.erb
<p><b>Province <%= @prov.name %></b>
</p>
<p>
Frekwencja:<br />
<%= @frekwencja %>

</p>

elections/app/views/provinces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Provinces</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mandate number</th>
      <th>Authorized number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @provinces.each do |province| %>
      <tr>
        <td><%= province.name %></td>
        <td><%= province.mandate_number %></td>
        <td><%= province.authorized_number %></td>
        <td><%= link_to 'Frekwencja', provinces_frekwencja_path(province) %></td>
        <td><%= link_to 'Show', province %></td>
        <td><%= link_to 'Edit', edit_province_path(province) %></td>
        <td><%= link_to 'Destroy', province, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Province', new_province_path %>

elections/app/views/provinces/new.html.erb
<h1>New Province</h1>

<%= render 'form' %>

<%= link_to 'Back', provinces_path %>

elections/app/views/provinces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @province.name %>
</p>
<p>
  <strong>Mandate number:</strong>
  <%= @province.mandate_number %>
</p>

<p>
  <strong>Authorized number:</strong>
  <%= @province.authorized_number %>
</p>

<%= link_to 'Edit', edit_province_path(@province) %> |
<%= link_to 'Back', provinces_path %>