elections/config/routes.rb
Rails.application.routes.draw do
get 'static/index'

devise_for :admin_users, ActiveAdmin::Devise.config
ActiveAdmin.routes(self)
resource :user_session, :only => [:new, :create, :destroy]
resources :users
resources :votes
resources :committees_provinces
resources :committees
resources :provinces
get 'provinces/:id/frekwencja' => 'provinces#frekwencja', :as => :provinces_frekwencja
resources :constituencies
get 'constituencies/:id/frekwencja' => 'constituencies#frekwencja', :as => :constituencies_frekwencja
resources :form
get 'list' => 'form#list', :as => :list
resources :formtwo, :only => [:index, :edit]
root :to => 'static#index'
get 'login' => 'user_sessions#new', :as => :login
get 'logout' => 'user_sessions#destroy', :as => :logout

end

elections/app/controllers/formtwo_controller.rb
class FormtwoController < ApplicationController

  def index
  	@user = current_user.constituency_id
    Constituency.where("id = ?", @user).each do |const|
    	@constituency = const
    end
  end

  def edit
    @constituenc = Constituency.find_by_id(current_user.constituency_id)
    
    if @constituenc.authorized_number ==nil
    	@constituenc.authorized_number =0
    end
    if @constituenc.mandate_number == nil
    	@constituenc.mandate_number =0
    end
    if @constituenc.given_cards==nil
    	@constituenc.given_cards=0
    end
    @prov= @constituenc.province_id
  end
  

  def update
  	@constituency = Constituency.find(params[:id])
    respond_to do |format|
      if @constituency.update_attributes(params[:constituency])
        format.html { redirect_to formtwo_index_path(current_user.constituency_id), notice: 'constituency was successfully updated.' }
        #format.json { render :index, status: :ok, location: @constituency }
      else
        format.html { render :edit }
        #format.json { render json: @constituency.errors, status: :unprocessable_entity }
      end
    end
  end
end

elections/app/views/formtwo/_form.html.erb
<%= form_for(@constituenc) do |f| %>
  <% if @constituency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@constituency.errors.count, "error") %> prohibited this constituency from being saved:</h2>

      <ul>
      <% @constituency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :empty_votes %><br>
    <%= f.number_field :empty_votes %>
  </div>
  <div class="field">
    <%= f.label :many_votes %><br>
    <%= f.number_field :many_votes %>
  </div>
  <div class="field">
    <%= f.label :other_votes %><br>
    <%= f.number_field :other_votes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

elections/app/views/formtwo/edit.html.erb
<h1>Edytuj ilość nieważnych głosów:</h1>
<%#= render 'form' %>

<%= form_for(@constituenc) do |f| %>
  <div class="field">
    <%#= f.label :name %><br>
    <%= f.hidden_field :name, :value => @constituenc.name %>
    <%#= f.label :authorized_number %><br>
    <%= f.hidden_field :authorized_number, :value => @constituenc.authorized_number %>
    <%= f.hidden_field :province_id, :value => @prov %>
    <%= f.hidden_field :mandate_number, :value => @constituenc.mandate_number %>
    <%= f.hidden_field :given_cards, :value => @constituenc.given_cards %>
  </div>
  <div class="field">
    <%= f.label :Liczba_pustych_kart_w_urnie %><br>
    <%= f.number_field :empty_votes %>
  </div>
  <div class="field">
    <%= f.label :Liczba_kart_ze_zbyt_dużą_ilością_głosów %><br>
    <%= f.number_field :many_votes %>
  </div>
  <div class="field">
    <%= f.label :Inne_przyczyny_nieważności_głosów %><br>
    <%= f.number_field :other_votes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

 <% end %> 

<%= link_to 'Back', formtwo_index_path %>

elections/app/views/formtwo/index.html.erb
<h1>Głosy nieważne dla okręgu: <strong><%= @constituency.name %><strong></h1>
  
  
  <table>
  <tr>
    <th>Liczba pustych kart w urnie:</th>
    <th>Liczba kart ze zbyt dużą ilością głosów:</th>
    <th>Inne przyczyny nieważności głosów:</th>
  </tr>
  <tr>
    <% if @constituency.empty_votes == nil && @constituency.many_votes==nil && @constituency.other_votes==nil  %>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    <% else %>
    <td><%= @constituency.empty_votes %></td>
    <td><%= @constituency.many_votes %></td>
    <td><%= @constituency.other_votes %></td>
    <% end %>
  </tr>
</table>
 <p><%= link_to 'Edit', edit_formtwo_path(@user) %></p><br>
 <h3><%= link_to 'wprowadź głosy ważne', form_index_path %></h3>

elections/app/views/formtwo/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Empty votes:</strong>
  <%= @constituency.empty_votes %>
</p>

<p>
  <strong>Many votes:</strong>
  <%= @constituency.many_votes %>
</p>

<p>
  <strong>Other votes:</strong>
  <%= @constituency.other_votes %>
</p>



<%= link_to 'Edit', edit_committees_province_path(@committees_province) %> |
<%= link_to 'Back', committees_provinces_path %>