elections/config/routes.rb
Rails.application.routes.draw do
get 'static/index'

devise_for :admin_users, ActiveAdmin::Devise.config
ActiveAdmin.routes(self)
resource :user_session, :only => [:new, :create, :destroy]
resources :users
resources :votes
resources :committees_provinces
resources :committees
resources :provinces
get 'provinces/:id/frekwencja' => 'provinces#frekwencja', :as => :provinces_frekwencja
resources :constituencies
get 'constituencies/:id/frekwencja' => 'constituencies#frekwencja', :as => :constituencies_frekwencja
resources :form
get 'list' => 'form#list', :as => :list
resources :formtwo, :only => [:index, :edit]
root :to => 'static#index'
get 'login' => 'user_sessions#new', :as => :login
get 'logout' => 'user_sessions#destroy', :as => :logout

end

elections/app/controllers/form_controller.rb
class FormController < ApplicationController
  protect_from_forgery with: :exception
  helper_method :current_user, :current_user_session
  
  def index
    @const =current_user.constituency_id
    Constituency.where("id = ?", @const).each do |con|
      @con = con.name
    end
    @votes = Vote.where("constituency_id = ?", @const)

  end

  def list
    @const = current_user.constituency_id
    @committees = Committee.all
    @vote = Vote.new
  end
  
  #def show
  #	@vote = Vote.find(params[:id])
  #end


  
 private

    def vote_params
      params.require(:vote).permit(:number, :committee_id, :constituency_id)
    end

  
  
end

elections/app/views/form/_form.html.erb
<%= form_for(@committee) do |f| %>
  <% if @committee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@committee.errors.count, "error") %> prohibited this committee from being saved:</h2>

      <ul>
      <% @committee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.text_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
   
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

elections/app/views/form/index.html.erb
<h1>Głosy ważne dla okręgu:<strong><%= @con %></strong> </h1>

<table>
  <thead>
    <tr>
      <th>Liczba głosów</th>
      <th>Nazwa partii</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.number %></td>
        <% if vote.committee %>
          <td><%= vote.committee.name %></td>
          <% else %>
            <td><%= vote.committee %></td>
        <% end %>
        <td><%= link_to 'Edytuj', edit_vote_path(vote) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<p>
<%= link_to 'dodaj nowy głos', list_path %>
<h3><%= link_to 'wprowadź głosy nieważne', formtwo_index_path %></h3>
</p>

elections/app/views/form/list.html.erb
<h1>Głosy ważne: </h1>
  <% @committees.each do |committee| %>
    <%= render "committees/committees_row", committee: committee %>
    <%= form_for(@vote) do |f| %>
    <%#form_for="vote.number"
    <p>Liczba głosów</p>
	<input type="number" name="vote.number" />%>
	<%= f.hidden_field :constituency_id, :value => @const %>
	<%= f.hidden_field :committee_id, :value => committee.id %>
	<div class="field">
    <%= f.label :Liczba_głosów %><br>
    <%= f.number_field :number %>
    </div>
    <div class="actions">
    <%= f.submit %>
    </div>
    <% end %>
  <% end %>

<p>
<%= link_to 'Powrót', form_index_path %>
</p>

elections/app/views/form/new.html.erb
<form action="vote.number">
	<p>Liczba głosów</p>
	<input type="number" name="vote.number" />
    </form>

elections/app/views/form/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Committee:</strong>
  <%= @committees_province.committee %>
</p>

<p>
  <strong>Province:</strong>
  <%= @committees_province.province %>
</p>

<%= link_to 'Edit', edit_committees_province_path(@committees_province) %> |
<%= link_to 'Back', committees_provinces_path %>