elections/config/routes.rb
Rails.application.routes.draw do
get 'static/index'

devise_for :admin_users, ActiveAdmin::Devise.config
ActiveAdmin.routes(self)
resource :user_session, :only => [:new, :create, :destroy]
resources :users
resources :votes
resources :committees_provinces
resources :committees
resources :provinces
get 'provinces/:id/frekwencja' => 'provinces#frekwencja', :as => :provinces_frekwencja
resources :constituencies
get 'constituencies/:id/frekwencja' => 'constituencies#frekwencja', :as => :constituencies_frekwencja
resources :form
get 'list' => 'form#list', :as => :list
resources :formtwo, :only => [:index, :edit]
root :to => 'static#index'
get 'login' => 'user_sessions#new', :as => :login
get 'logout' => 'user_sessions#destroy', :as => :logout

end

elections/app/models/constituency.rb
class Constituency < ActiveRecord::Base
  belongs_to :province

  validates :name, presence: true
  validates :mandate_number, presence: true, numericality: true
  validates :authorized_number, presence: true, numericality: true
  validates :empty_votes, presence: true, numericality: true
  validates :many_votes, presence: true, numericality: true
  validates :other_votes, presence: true, numericality: true
  validates :given_cards, presence: true, numericality: true
 

  def set_constituencies
    @constituencies = Constituency.all.map do |constituency|
      [ constituency.name, constituency.id]
    return @constituencies
  end
end
  def constituency_params
      params.require(:constituency).permit(:name, :mandate_number, :authorized_number, :empty_votes, :many_votes, :other_votes, :given_cards, :province_id)
    end
end

elections/app/controllers/constituencies_controller.rb
class ConstituenciesController < InheritedResources::Base
  #load_and_authorize_resource
  def show
    @constituency = Constituency.find(params[:id])
  end
  def edit
  	@constituency = Constituency.find(params[:id])
  end
  def update
    @constituency = Constituency.find(params[:id])
    respond_to do |format|
      if @constituency.update_attributes(constituency_params)
        format.html { redirect_to formtwo_index_path, notice: 'constituency was successfully updated.' }
        #format.json { render :, status: :ok, location: @constituency }
      else
        format.html { render :edit }
        #format.json { render json: @constituency.errors, status: :unprocessable_entity }
      end
    end
  end

  def frekwencja 
    @con = Constituency.find_by_id(params[:id]) 
    @constituency = Constituency.where("province_id = ? AND given_cards IS NOT NULL", params[:id]) 
    @voters = @constituency.sum(:authorized_number) 
    @cards = @constituency.sum(:given_cards) 
    if @voters != 0 && @cards!= 0 
      @frekwencja = @cards*100/@voters 
    else 
      @frekwencja = 0 
    end 
  end
  private

    def constituency_params
      params.require(:constituency).permit(:name, :mandate_number, :authorized_number, :empty_votes, :many_votes, :other_votes, :given_cards, :province_id)
    end
end

elections/app/helpers/constituencies_helper.rb
module ConstituenciesHelper
end

elections/app/views/constituencies/_form.html.erb
<%= form_for(@constituency) do |f| %>
  <% if @constituency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@constituency.errors.count, "error") %> prohibited this constituency from being saved:</h2>

      <ul>
      <% @constituency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mandate_number %><br>
    <%= f.number_field :mandate_number %>
  </div>
  <div class="field">
    <%= f.label :authorized_number %><br>
    <%= f.number_field :authorized_number %>
  </div>
  <div class="field">
    <%= f.label :empty_votes %><br>
    <%= f.number_field :empty_votes %>
  </div>
  <div class="field">
    <%= f.label :many_votes %><br>
    <%= f.number_field :many_votes %>
  </div>
  <div class="field">
    <%= f.label :other_votes %><br>
    <%= f.number_field :other_votes %>
  </div>
  <div class="field">
    <%= f.label :given_cards %><br>
    <%= f.number_field :given_cards %>
  </div>
  <div class="field">
    <%= f.label :province_id %><br>
    <%= f.text_field :province_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

elections/app/views/constituencies/edit.html.erb
<h1>Editing Constituency</h1>

<%= render 'form' %>

<%= link_to 'Show', @constituency %> |
<%= link_to 'Back', constituencies_path %>

elections/app/views/constituencies/frekwencja.html.erb
<p><b>Constituency <%= @con.name %></b>
</p>
<p>
Frekwencja:<br />
<%= @frekwencja %>%

</p>
<%= link_to 'Listing constituencies', constituencies_path %>

elections/app/views/constituencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Constituencies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mandate number</th>
      <th>Authorized number</th>
      <th>Empty votes</th>
      <th>Many votes</th>
      <th>Other votes</th>
      <th>Given cards</th>
      <th>Province</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @constituencies.each do |constituency| %>
      <tr>
        <td><%= constituency.name %></td>
        <td><%= constituency.mandate_number %></td>
        <td><%= constituency.authorized_number %></td>
        <td><%= constituency.empty_votes %></td>
        <td><%= constituency.many_votes %></td>
        <td><%= constituency.other_votes %></td>
        <td><%= constituency.given_cards %></td>
        <% if constituency.province %>
          <td><%= constituency.province.name %></td>
          <% else %>
            <td><%= constituency.province %></td>
        <% end %>
        <td><%= link_to 'Frekwencja', constituencies_frekwencja_path(constituency) %></td>
        <td><%= link_to 'Show', constituency %></td>
        <td><%= link_to 'Edit', edit_constituency_path(constituency) %></td>
        <td><%= link_to 'Destroy', constituency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Constituency', new_constituency_path %>

elections/app/views/constituencies/new.html.erb
<h1>New Constituency</h1>

<%= render 'form' %>

<%= link_to 'Back', constituencies_path %>

elections/app/views/constituencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @constituency.name %>
</p>

<p>
  <strong>Mandate number:</strong>
  <%= @constituency.mandate_number %>
</p>

<p>
  <strong>Authorized number:</strong>
  <%= @constituency.authorized_number %>
</p>

<p>
  <strong>Empty votes:</strong>
  <%= @constituency.empty_votes %>
</p>

<p>
  <strong>Many votes:</strong>
  <%= @constituency.many_votes %>
</p>

<p>
  <strong>Other votes:</strong>
  <%= @constituency.other_votes %>
</p>

<p>
  <strong>Given cards:</strong>
  <%= @constituency.given_cards %>
</p>

<p>
  <strong>Province:</strong>
  <%= @constituency.province.name %>
</p>

<%= link_to 'Edit', edit_constituency_path(@constituency) %> |
<%= link_to 'Back', constituencies_path %>